# Generated by Django 2.2.2 on 2019-09-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageplace',
            name='contents_weight_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplace',
            name='empty_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplace',
            name='inside_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplace',
            name='inside_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplace',
            name='inside_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplace',
            name='outside_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplace',
            name='outside_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplace',
            name='outside_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
